---
- name: Zookeeper | Create dataDir and logDir
  file:
    path: "{{ item }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    state: directory
  with_items:
    - "{{ zk_dataDir }}"
    - "{{ zk_logDir }}"

- name: Zookeeper | Copy zoo.cfg file
  template: 
    src: templates/zoo.cfg.j2
    dest: "{{ zk_home_dir }}/{{ zk_user }}/conf/zoo.cfg"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
  with_items: "{{ groups['zookeeper'] }}"
  notify: restart zookeeper

- name: Zookeeper | Create myid file
  template:
    src: templates/myid.j2
    dest: "{{ zk_dataDir }}/myid"
  ignore_errors: True
  notify: restart zookeeper

- name: Zookeeper | Copy systemd file
  template:
    src: templates/zookeeper.service.j2
    dest: "/etc/systemd/system/{{ zk_user }}.service"
    owner: root
    group: root

- name: Zookeeper | Start Zookeeper Service
  service:
    name: "{{ zk_user }}"
    state: "{{ zk_state }}"
    enabled: yes
    daemon_reload: yes
