---
- name: Zookepeer | Ensure Group
  group:
    name: "{{ zk_group }}"

- name: Zookepeer | Ensure User
  user:
    name: "{{ zk_user }}"
    group: "{{ zk_group }}"
    comment: "{{ zk_user }} system user"
    home: "/home/{{ zk_user }}"
    system: yes

### Use this task for 
#- name: Zookepeer | Copy binary package
#  copy:
#    src: "files/{{ zk_package }}"
#    dest: "{{ zk_tmp_dir }}/{{ zk_package }}"

- name: Zookepeer | Extract
  unarchive:
    src: "{{ zk_get_url }}"
    dest: "{{ zk_home_dir }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    remote_src: yes
    creates: "{{ zk_home_dir }}/{{ zk_user }}/conf/zoo.cfg"

- name: Zookepeer | Create symbolic link
  file:
    src: "{{ zk_home_dir }}/zookeeper-{{ zk_version }}"
    dest: "{{ zk_home_dir }}/{{ zk_user }}"
    state: link
    force: yes

- name: Zookeeper | Remove binary package 
  file: 
    path: "{{ zk_tmp_dir }}/{{ zk_package }}"
    state: absent
