---
- name: Zookeeper | Copy systemd file
  template:
    src: templates/zookeeper.service.j2
    dest: "/etc/systemd/system/{{zk_user}}.service"
    owner: root
    group: root
  tags: zookeeper

- name: Zookeeper | Create dataDir and logDir
  file:
    path: "{{item}}"
    owner: "{{zk_user}}"
    group: "{{zk_group}}"
    state: directory
    recurse: yes
    force: yes
  with_items:
    - "{{zk_dataDir}}"
    - "{{zk_logDir}}"
  tags: zookeeper

- name: Zookeeper | Copy zoo.cfg file
  template: 
    src: templates/zoo.cfg.j2
    dest: "{{zk_home_dir}}/{{zk_user}}/conf/zoo.cfg"
    owner: "{{zk_user}}"
    group: "{{zk_group}}"
  notify: restart zookeeper
  with_items: "{{groups['zookeeper']}}"
  tags: zookeeper

- name: Zookeeper | Configure zookeeper-env.sh
  template: 
    src: templates/zookeeper-env.sh.j2 
    dest: "{{ zk_conf_dir }}/zookeeper-env.sh"
    owner: "{{zk_user}}" 
    group: "{{zk_group}}"
  notify:
    - restart zookeeper
  when: zk_env is defined and zk_env|length > 0
  tags: env-file 
  tags: zookeeper

- name: Zookeeper | Create myid file
  template:
    src: templates/myid.j2
    dest: "{{zk_dataDir}}/myid"
  notify: restart zookeeper
  tags: zookeeper

- name: Zookeeper | Start Zookeeper Service
  service:
    name: "{{zk_user}}"
    state: "{{zk_state}}"
    enabled: yes
    daemon_reload: yes
  tags: zookeeper
