---
- name: Zookepeer | Ensure Group
  group:
    name: "{{zk_group}}"
  tags: zookeeper

- name: Zookepeer | Ensure User
  user:
    name: "{{zk_user}}"
    group: "{{zk_group}}"
    comment: "{{ zk_user }} system user"
    home: "/home/{{zk_user}}"
    system: yes
  tags: zookeeper

- name: Zookepeer | Download and Extract package
  unarchive:
    src: "{{zk_get_url}}"
    dest: "{{zk_install_dir}}"
    owner: "{{zk_user}}"
    group: "{{zk_group}}"
    remote_src: yes
    creates: "{{zk_install_dir}}/{{zk_inst_name}}/conf/zoo.cfg"
  tags: zookeeper

- name: Zookepeer | Create symbolic link
  file:
    src: "{{zk_install_dir}}/zookeeper-{{zk_version}}"
    dest: "{{zk_install_dir}}/{{zk_inst_name}}"
    state: link
    force: yes
  tags: zookeeper
