---
- name: SolrCloud | Ensure dependencies are installed.
  package: name={{ item }} state=present
  with_items:
    - lsof
    - wget
    - vim

- name: SolrCloud | Ensure Solr Group
  group: 
    name: "{{ solr_group }}"

- name: SolrCloud | Ensure Solr User
  user:
    name: "{{solr_user}}"
    group: "{{solr_group}}"
    home: "/home/{{solr_user}}"
    createhome: yes

- name: SolrCloud | Extract Package
  unarchive:
    src: "{{solr_get_url}}"
    dest: "{{solr_home_dir}}"
    owner: "{{solr_user}}"
    group: "{{solr_group}}"
    remote_src: yes
    creates: "{{solr_home_dir}}/solr-{{solr_version}}/bin/solr"

- name: SolrCloud | Create symbol link
  file:
    src: "{{solr_home_dir}}/solr-{{solr_version}}"
    dest: "{{solr_home_dir}}/{{solr_user}}"
    state: link
    force: yes

- name: SolrCloud | Ensure Solr dirs exists
  file:
    path: "{{item}}"
    state: directory
    owner: "{{solr_user}}"
    group: "{{solr_group}}"
  with_items:
    - "{{ solr_logDir }}"
    - "{{ solr_dataDir }}"
