---
# group_vars/solrcloud

- name: SolrCloud | Ensure dependencies are installed.
  package: name="{{item}}" state=present
  with_items:
    - lsof
    - wget
    - vim
  tags: solrcloud

- name: SolrCloud | Ensure Solr Group
  group: 
    name: "{{solr_group}}"
  tags: solrcloud

- name: SolrCloud | Ensure Solr User
  user:
    name: "{{solr_user}}"
    group: "{{solr_group}}"
    home: "/home/{{solr_user}}"
    createhome: yes
  tags: solrcloud

- name: SolrCloud | Extract Package
  unarchive:
    src: "{{solr_get_url}}"
    dest: "{{solr_install_dir}}"
    owner: "{{solr_user}}"
    group: "{{solr_group}}"
    remote_src: yes
    creates: "{{solr_install_dir}}/solr-{{solr_version}}/bin/solr"
  tags: solrcloud

- name: SolrCloud | Create symbol link
  file:
    src: "{{solr_install_dir}}/solr-{{solr_version}}"
    dest: "{{solr_install_dir}}/{{solr_inst_name}}"
    state: link
    force: yes
  tags: solrcloud

- name: SolrCloud | Ensure Solr dirs exists
  file:
    path: "{{item}}"
    state: directory
    owner: "{{solr_user}}"
    group: "{{solr_group}}"
  with_items:
    - "{{ solr_logDir }}"
    - "{{ solr_dataDir }}"
  tags: solrcloud
