---
- name: Instalando os pre-requisitos
  hosts: all
  become: True

  roles:
    - roles/common 
    - roles/oracle-java8
#    - roles/filesystem

- name: Configurando o Zookeeper
  hosts: zookeeper

  roles:
    - roles/zookeeper

- name: Configurando o SolrCloud
  hosts: solrcloud
  
  roles:
    - roles/solrcloud
