---
- name: Instalando os pre-requisitos
  hosts: all
  become: True

  roles:
    - { role: roles/oracle-java8, when: ansible_os_family == 'RedHat' }
    - { role: roles/common, when: ansible_os_family == 'RedHat' }

- name: Configurando o Zookeeper
  hosts: zookeeper
  become: True

  roles:
    - { role: roles/zookeeper, when: ansible_os_family == 'RedHat' }

- name: Configurando o SolrCloud
  hosts: solrcloud
  become: True
  roles:
    - { role: roles/solrcloud, when: ansible_os_family == 'RedHat' }
