---
- name: Zookepeer | Ensure Group
  group:
    name: "{{ zk_group }}"

- name: Zookepeer | Ensure User
  user:
    name: "{{ zk_user }}"
    group: "{{ zk_group }}"
    home: "/bin/false"
    system: yes

- name: Zookepeer | Copy binary package
  copy:
    src: "files/{{ zk_package }}"
    dest: "{{ zk_tmp_dir }}/{{ zk_package }}"

- name: Zookepeer | Extract
  unarchive:
    src: "{{ zk_tmp_dir }}/{{ zk_package }}"
    dest: "{{ zk_home_dir }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    remote_src: yes

- name: Zookepeer | Create symbol link
  file:
    src: "{{ zk_home_dir }}/zookeeper-{{ zk_version }}"
    dest: "{{ zk_home_dir }}/{{ zk_user }}"
    state: link
    force: yes

- name: Zookeeper | Remove binary package 
  file: 
    path: "{{ zk_tmp_dir }}/{{ zk_package }}"
    state: absent
